apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paddleocr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paddleocr
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 750m
